# Generated by Django 4.2 on 2023-04-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_days_review_customuser_days_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.flashcarddeck'),
        ),
    ]
